<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260830104834 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ordre_de_fabrication (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recette VARCHAR(255) NOT NULL, lots INT NOT NULL, duree_en_cycles INT NOT NULL, avancement_en_dixiemes INT NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ORDRE_PAR_VILLE ON ordre_de_fabrication (ville_id)');
        $this->addSql('ALTER TABLE ordre_de_fabrication ADD CONSTRAINT FK_9818FC3EA73F0036 FOREIGN KEY (ville_id) REFERENCES city (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ordre_de_fabrication DROP CONSTRAINT FK_9818FC3EA73F0036');
        $this->addSql('DROP TABLE ordre_de_fabrication');
    }
}
