<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Le seuil de garde du Marché et les présents du pharaon.
 *
 * `reserve_gardee` : ce que la ville garde d'une ressource, et en deçà de quoi
 * elle ne vend jamais. Tout ce qui dépasse part au Marché de lui-même. Sans
 * cela, le Marché ne rapportait un deben que si le joueur venait cliquer à
 * chaque quinzaine, et une partie jouée normalement n'en produisait aucun.
 *
 * `present_royal` : ce que le roi renvoie pour une demande de chantier
 * honorée, et qui remonte le fleuve pendant quelques quinzaines.
 *
 * Deux tables neuves, aucune donnée existante à convertir.
 */
final class Version20260903171646 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Seuil de garde du Marché et présents du pharaon.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE present_royal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ressource VARCHAR(255) NOT NULL, quantite INT NOT NULL, quinzaines_avant_arrivee INT NOT NULL, chantier VARCHAR(255) NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F4F36944A73F0036 ON present_royal (ville_id)');
        $this->addSql('CREATE TABLE reserve_gardee (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ressource VARCHAR(255) NOT NULL, quantite_gardee INT NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9DBBB6A6A73F0036 ON reserve_gardee (ville_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_RESERVE_GARDEE_PAR_VILLE ON reserve_gardee (ville_id, ressource)');
        $this->addSql('ALTER TABLE present_royal ADD CONSTRAINT FK_F4F36944A73F0036 FOREIGN KEY (ville_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reserve_gardee ADD CONSTRAINT FK_9DBBB6A6A73F0036 FOREIGN KEY (ville_id) REFERENCES city (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE present_royal DROP CONSTRAINT FK_F4F36944A73F0036');
        $this->addSql('ALTER TABLE reserve_gardee DROP CONSTRAINT FK_9DBBB6A6A73F0036');
        $this->addSql('DROP TABLE present_royal');
        $this->addSql('DROP TABLE reserve_gardee');
    }
}
