<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260830152401 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE convoi (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ressource VARCHAR(255) NOT NULL, sens VARCHAR(255) NOT NULL, quantite INT NOT NULL, prix INT NOT NULL, quinzaines_avant_retour INT NOT NULL, route_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_794E068D34ECB4E6 ON convoi (route_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CONVOI_PAR_ROUTE ON convoi (route_id, ressource)');
        $this->addSql('ALTER TABLE convoi ADD CONSTRAINT FK_794E068D34ECB4E6 FOREIGN KEY (route_id) REFERENCES route_commerciale (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE convoi DROP CONSTRAINT FK_794E068D34ECB4E6');
        $this->addSql('DROP TABLE convoi');
    }
}
