<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * La lignée : ce qu'un joueur a acquis au fil de ses parties (doc 13, lot 9.1).
 *
 * Elle est **rétro-alimentée** à la création : un joueur qui a déjà mené des
 * missions à leur terme ne doit pas voir son acquis repartir de zéro le jour où
 * la table apparaît. On reprend la plus haute renommée qu'une de ses parties de
 * campagne achevées portait — exactement ce que `Lignees::encaisser()` aurait
 * versé si elle avait existé alors.
 */
final class Version20260902205146 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée la lignée, acquis de renommée persistant d\'une mission à l\'autre.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE lignee (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, renommee_acquise INT NOT NULL, joueur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9B3C581BA9E2D76C ON lignee (joueur_id)');
        $this->addSql('ALTER TABLE lignee ADD CONSTRAINT FK_9B3C581BA9E2D76C FOREIGN KEY (joueur_id) REFERENCES "user" (id) NOT DEFERRABLE');

        // Rétro-alimentation : la plus haute renommée atteinte sur une mission
        // de campagne achevée. Les joueurs sans partie achevée n'ont pas de
        // lignée — elle naîtra à leur prochain lancement.
        $this->addSql(<<<'SQL'
            INSERT INTO lignee (joueur_id, renommee_acquise)
            SELECT g.joueur_id, MAX(f.renommee)
            FROM game_save g
            INNER JOIN family f ON f.id = g.famille_id
            WHERE g.statut = 'achevee' AND g.mode = 'campagne'
            GROUP BY g.joueur_id
            SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE lignee DROP CONSTRAINT FK_9B3C581BA9E2D76C');
        $this->addSql('DROP TABLE lignee');
    }
}
