<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260827164559 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE zone (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, x INT NOT NULL, y INT NOT NULL, terrain VARCHAR(255) NOT NULL, contenu VARCHAR(255) NOT NULL, ressource VARCHAR(255) DEFAULT NULL, quantite_restante INT NOT NULL, decouverte BOOLEAN NOT NULL, porte_la_ville BOOLEAN NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A0EBC007A73F0036 ON zone (ville_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ZONE_PAR_VILLE ON zone (ville_id, x, y)');
        $this->addSql('ALTER TABLE zone ADD CONSTRAINT FK_A0EBC007A73F0036 FOREIGN KEY (ville_id) REFERENCES city (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE zone DROP CONSTRAINT FK_A0EBC007A73F0036');
        $this->addSql('DROP TABLE zone');
    }
}
