<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * La population se compte en trois nombres, plus en maisonnées (lot 4.1, révisé).
 *
 * Le modèle précédent suivait chaque foyer et l'âge de chacun de ses enfants.
 * La joueuse a tranché pour l'inverse : aucune granularité fine, seulement des
 * habitants, des actifs et des inactifs, dont le bilan se fait une fois l'an.
 * La table `foyer` disparaît donc au profit de trois colonnes sur `city`.
 */
final class Version20260828145239 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Remplace la table foyer par les compteurs actifs / enfants / anciens de la ville.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE city ADD actifs INT NOT NULL DEFAULT 0');
        $this->addSql('ALTER TABLE city ADD enfants INT NOT NULL DEFAULT 0');
        $this->addSql('ALTER TABLE city ADD anciens INT NOT NULL DEFAULT 0');

        // Les parties en cours reçoivent la troupe de volontaires que le
        // pharaon envoie désormais à l'ouverture. C'est une **réparation, pas
        // une invention** : ce contingent fait partie des conditions de départ,
        // et une ville créée avant la règle ne l'a jamais reçu. Recopier à la
        // place les deux adultes de l'ancienne table lui laisserait une
        // population qui ne peut plus croître — sans enfant à faire mûrir et
        // sans naissance, elle s'éteindrait lentement.
        $this->addSql('UPDATE city SET actifs = 4, enfants = 5, anciens = 1');

        $this->addSql('ALTER TABLE city ALTER actifs DROP DEFAULT');
        $this->addSql('ALTER TABLE city ALTER enfants DROP DEFAULT');
        $this->addSql('ALTER TABLE city ALTER anciens DROP DEFAULT');

        $this->addSql('ALTER TABLE foyer DROP CONSTRAINT fk_4eb44e88a73f0036');
        $this->addSql('DROP TABLE foyer');
    }

    /**
     * Le retour en arrière rend une maisonnée par ville, avec ses adultes mais
     * sans ses enfants : les âges individuels n'existent plus nulle part, et
     * les réinventer serait pire que de les omettre.
     */
    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE foyer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, adultes INT NOT NULL, ages_des_enfants JSON NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_4eb44e88a73f0036 ON foyer (ville_id)');
        $this->addSql('ALTER TABLE foyer ADD CONSTRAINT fk_4eb44e88a73f0036 FOREIGN KEY (ville_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql("INSERT INTO foyer (ville_id, adultes, ages_des_enfants) SELECT id, GREATEST(actifs, 1), '[]' FROM city");

        $this->addSql('ALTER TABLE city DROP actifs');
        $this->addSql('ALTER TABLE city DROP enfants');
        $this->addSql('ALTER TABLE city DROP anciens');
    }
}
