<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260827160653 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE chantier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, niveau_vise INT NOT NULL, duree_en_cycles INT NOT NULL, avancement_en_dixiemes INT NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_636F27F6A73F0036 ON chantier (ville_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CHANTIER_PAR_VILLE ON chantier (ville_id, type)');
        $this->addSql('ALTER TABLE chantier ADD CONSTRAINT FK_636F27F6A73F0036 FOREIGN KEY (ville_id) REFERENCES city (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE chantier DROP CONSTRAINT FK_636F27F6A73F0036');
        $this->addSql('DROP TABLE chantier');
    }
}
