<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * La table des faveurs divines (lot 6.0).
 *
 * Rien à reprendre sur les parties existantes : une divinité sans ligne est
 * neutre, ce qui est exactement l'état d'une ville qui n'a jamais offert.
 */
final class Version20260830162106 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Faveur divine : une ligne par dieu réellement honoré';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE faveur_divine (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, divinite VARCHAR(20) NOT NULL, faveur INT NOT NULL, quinzaines_sans_offrande INT NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7AA339AAA73F0036 ON faveur_divine (ville_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FAVEUR_PAR_VILLE ON faveur_divine (ville_id, divinite)');
        $this->addSql('ALTER TABLE faveur_divine ADD CONSTRAINT FK_7AA339AAA73F0036 FOREIGN KEY (ville_id) REFERENCES city (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE faveur_divine DROP CONSTRAINT FK_7AA339AAA73F0036');
        $this->addSql('DROP TABLE faveur_divine');
    }
}
