<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Les quêtes de chantier du pharaon (lot 8.3).
 *
 * Rien à reprendre : aucune ville n'en a reçu — le pharaon n'en réclamait pas
 * encore.
 */
final class Version20260901105636 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Quêtes de chantier : ce que le pharaon réclame pour ses monuments';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE quete_de_chantier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, chantier VARCHAR(40) NOT NULL, ressource VARCHAR(40) NOT NULL, quantite INT NOT NULL, quinzaines_restantes INT NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_QUETE_PAR_VILLE ON quete_de_chantier (ville_id)');
        $this->addSql('ALTER TABLE quete_de_chantier ADD CONSTRAINT FK_2CEEAD32A73F0036 FOREIGN KEY (ville_id) REFERENCES city (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE quete_de_chantier DROP CONSTRAINT FK_2CEEAD32A73F0036');
        $this->addSql('DROP TABLE quete_de_chantier');
    }
}
