<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260830124126 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ordre_commercial (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ressource VARCHAR(255) NOT NULL, sens VARCHAR(255) NOT NULL, prix INT NOT NULL, quantite_par_convoi INT NOT NULL, route_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_747DAA0A34ECB4E6 ON ordre_commercial (route_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ORDRE_PAR_ROUTE ON ordre_commercial (route_id, ressource)');
        $this->addSql('ALTER TABLE ordre_commercial ADD CONSTRAINT FK_747DAA0A34ECB4E6 FOREIGN KEY (route_id) REFERENCES route_commerciale (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ordre_commercial DROP CONSTRAINT FK_747DAA0A34ECB4E6');
        $this->addSql('DROP TABLE ordre_commercial');
    }
}
