<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Les marchands rivaux (lot 7.8).
 *
 * Rien à reprendre : aucune ville existante n'a de rival — une seule rivalité
 * à la fois, et elle naît de la renommée.
 */
final class Version20260901095825 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Rivaux commerciaux : un marchand installé sur une route';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE rival_commercial (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, partenaire VARCHAR(40) NOT NULL, nom VARCHAR(60) NOT NULL, malus_en_centiemes INT NOT NULL, quinzaines_restantes INT NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_RIVAL_PAR_VILLE ON rival_commercial (ville_id)');
        $this->addSql('ALTER TABLE rival_commercial ADD CONSTRAINT FK_123EE738A73F0036 FOREIGN KEY (ville_id) REFERENCES city (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE rival_commercial DROP CONSTRAINT FK_123EE738A73F0036');
        $this->addSql('DROP TABLE rival_commercial');
    }
}
