<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * La troupe levée à la Caserne (doc 03, lot 10.2).
 *
 * Un Medjaÿ n'est pas un `Employee` : le chef a une compétence, un salaire
 * négocié et une maisonnée, le Medjaÿ a une force, une spécialisation et une
 * expérience gagnée au combat. Les deux n'ont en commun qu'un salaire, ce qui
 * ne suffisait pas à en faire une seule table.
 *
 * Rattachée à la ville et emportée avec elle (cascade sur `City`), comme tout
 * ce qui appartient à une partie.
 */
final class Version20260902214218 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée la troupe de Medjaÿ levée à la Caserne.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE medjay (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, specialisation VARCHAR(255) NOT NULL, experience INT NOT NULL, retabli_au_cycle INT DEFAULT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F041F8C6A73F0036 ON medjay (ville_id)');
        $this->addSql('ALTER TABLE medjay ADD CONSTRAINT FK_F041F8C6A73F0036 FOREIGN KEY (ville_id) REFERENCES city (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE medjay DROP CONSTRAINT FK_F041F8C6A73F0036');
        $this->addSql('DROP TABLE medjay');
    }
}
