<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Une parcelle par champ, chacune avec sa culture et son propre cycle.
 *
 * Une case portait **un** champ — une culture, un semis. Elle en porte
 * désormais jusqu'à quatre, indépendants : on sème du blé à côté de l'orge sur
 * le même limon, et chacun mûrit à son rythme.
 *
 * **Les champs existants sont convertis, jamais perdus** : chaque case semée
 * donne autant de parcelles qu'elle comptait de champs, toutes de sa culture et
 * au même point de son cycle. C'est exactement l'état d'avant, exprimé dans le
 * nouveau modèle — une partie en cours ne voit aucune différence au
 * chargement.
 *
 * La conversion se fait **avant** de laisser tomber les colonnes de `zone` :
 * l'ordre est ce qui distingue une migration d'une perte de données.
 */
final class Version20260903182805 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Une parcelle par champ, avec sa culture et son cycle propres.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE parcelle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rang INT NOT NULL, culture VARCHAR(255) NOT NULL, quinzaines_depuis_semis INT DEFAULT NULL, zone_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C56E2CF69F2C3FAB ON parcelle (zone_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PARCELLE_PAR_RANG ON parcelle (zone_id, rang)');
        $this->addSql('ALTER TABLE parcelle ADD CONSTRAINT FK_C56E2CF69F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id) NOT DEFERRABLE');
        // La conversion, avant tout retrait : une case semée donne autant de
        // parcelles qu'elle comptait de champs, toutes de sa culture et au même
        // point de son cycle agricole.
        $this->addSql(<<<'SQL'
            INSERT INTO parcelle (zone_id, rang, culture, quinzaines_depuis_semis)
            SELECT z.id, rangs.rang, z.culture, z.quinzaines_depuis_semis
            FROM zone z
            CROSS JOIN LATERAL generate_series(1, GREATEST(z.champs, 1)) AS rangs(rang)
            WHERE z.culture IS NOT NULL
            SQL);

        $this->addSql('ALTER TABLE zone DROP culture');
        $this->addSql('ALTER TABLE zone DROP quinzaines_depuis_semis');
        $this->addSql('ALTER TABLE zone DROP champs');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE zone ADD culture VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE zone ADD quinzaines_depuis_semis INT DEFAULT NULL');
        $this->addSql('ALTER TABLE zone ADD champs INT DEFAULT 1 NOT NULL');

        // **On relit avant de détruire.** Le retour en arrière ne peut garder
        // qu'une culture par case — c'est la limite du modèle d'avant, et il
        // faut la dire plutôt que de la laisser découvrir : on retient celle du
        // premier rang, et le nombre de champs.
        $this->addSql(<<<'SQL'
            UPDATE zone z SET
                culture = p.culture,
                quinzaines_depuis_semis = p.quinzaines_depuis_semis,
                champs = (SELECT COUNT(*) FROM parcelle WHERE zone_id = z.id)
            FROM parcelle p
            WHERE p.zone_id = z.id AND p.rang = (SELECT MIN(rang) FROM parcelle WHERE zone_id = z.id)
            SQL);

        $this->addSql('ALTER TABLE parcelle DROP CONSTRAINT FK_C56E2CF69F2C3FAB');
        $this->addSql('DROP TABLE parcelle');
    }
}
