<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Une case porte désormais plusieurs gisements (décision de la joueuse).
 *
 * À un gisement par case, l'argile et les roseaux — les deux matériaux dont
 * rien ne tient lieu, tous deux nés de l'eau — se disputaient les rares berges
 * d'une petite carte, au point qu'une partie pouvait se figer faute de l'un des
 * deux. Les trois colonnes de `zone` deviennent donc une table à part.
 */
final class Version20260827212928 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Les gisements quittent la table zone : une case peut en porter plusieurs.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE gisement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ressource VARCHAR(255) NOT NULL, quantite_restante INT NOT NULL, exploitee BOOLEAN NOT NULL, zone_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_56002DB69F2C3FAB ON gisement (zone_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_GISEMENT_PAR_ZONE ON gisement (zone_id, ressource)');
        $this->addSql('ALTER TABLE gisement ADD CONSTRAINT FK_56002DB69F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id) NOT DEFERRABLE');
        // Les gisements déjà posés sur les cartes en cours sont repris tels
        // quels : une partie entamée ne doit pas perdre ses filons.
        $this->addSql(
            'INSERT INTO gisement (zone_id, ressource, quantite_restante, exploitee)
             SELECT id, ressource, quantite_restante, exploitee
             FROM zone
             WHERE ressource IS NOT NULL',
        );

        $this->addSql('ALTER TABLE zone DROP ressource');
        $this->addSql('ALTER TABLE zone DROP quantite_restante');
        $this->addSql('ALTER TABLE zone DROP exploitee');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE zone ADD ressource VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE zone ADD quantite_restante INT NOT NULL DEFAULT 0');
        $this->addSql('ALTER TABLE zone ADD exploitee BOOLEAN NOT NULL DEFAULT FALSE');

        // Le retour en arrière ne peut garder qu'un gisement par case : c'est
        // toute la raison d'être de cette migration. Le premier est conservé,
        // les autres sont perdus.
        $this->addSql(
            'UPDATE zone z SET ressource = g.ressource, quantite_restante = g.quantite_restante, exploitee = g.exploitee
             FROM (SELECT DISTINCT ON (zone_id) zone_id, ressource, quantite_restante, exploitee
                   FROM gisement ORDER BY zone_id, id) g
             WHERE g.zone_id = z.id',
        );

        $this->addSql('ALTER TABLE zone ALTER quantite_restante DROP DEFAULT');
        $this->addSql('ALTER TABLE zone ALTER exploitee DROP DEFAULT');
        $this->addSql('ALTER TABLE gisement DROP CONSTRAINT FK_56002DB69F2C3FAB');
        $this->addSql('DROP TABLE gisement');
    }
}
