<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * La consigne permanente des ateliers.
 *
 * Ce que l'Atelier et la Forge refont d'eux-mêmes dès qu'ils se libèrent. Sans
 * elle, un ordre tenait une à trois quinzaines puis le bâtiment s'arrêtait et
 * attendait qu'on revienne le relancer à la main — sur une partie où l'on
 * passe des quinzaines entières sur la carte, les deux dormaient l'essentiel
 * du temps.
 *
 * Table neuve, aucune donnée existante à convertir.
 */
final class Version20260903173219 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Consigne permanente des ateliers.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE consigne_de_fabrication (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, batiment VARCHAR(255) NOT NULL, recette VARCHAR(255) NOT NULL, lots INT NOT NULL, en_attente_de_matieres BOOLEAN NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5880B819A73F0036 ON consigne_de_fabrication (ville_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CONSIGNE_PAR_BATIMENT ON consigne_de_fabrication (ville_id, batiment)');
        $this->addSql('ALTER TABLE consigne_de_fabrication ADD CONSTRAINT FK_5880B819A73F0036 FOREIGN KEY (ville_id) REFERENCES city (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE consigne_de_fabrication DROP CONSTRAINT FK_5880B819A73F0036');
        $this->addSql('DROP TABLE consigne_de_fabrication');
    }
}
