<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260827163709 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE stock_de_ressource (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ressource VARCHAR(255) NOT NULL, quantite INT NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6DE01D5EA73F0036 ON stock_de_ressource (ville_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_RESSOURCE_PAR_VILLE ON stock_de_ressource (ville_id, ressource)');
        $this->addSql('ALTER TABLE stock_de_ressource ADD CONSTRAINT FK_6DE01D5EA73F0036 FOREIGN KEY (ville_id) REFERENCES city (id) NOT DEFERRABLE');
        // Reprise du stock existant avant de perdre les colonnes : une ligne
        // par ressource réellement détenue, les stocks nuls sont ignorés.
        foreach (['stock_or' => 'or', 'bois' => 'bois', 'pierre' => 'pierre'] as $colonne => $ressource) {
            $this->addSql(sprintf(
                'INSERT INTO stock_de_ressource (ville_id, ressource, quantite)
                 SELECT id, %s, %s FROM city WHERE %s > 0',
                $this->connection->quote($ressource),
                $colonne,
                $colonne,
            ));
        }

        $this->addSql('ALTER TABLE city DROP stock_or');
        $this->addSql('ALTER TABLE city DROP bois');
        $this->addSql('ALTER TABLE city DROP pierre');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE stock_de_ressource DROP CONSTRAINT FK_6DE01D5EA73F0036');
        $this->addSql('DROP TABLE stock_de_ressource');
        $this->addSql('ALTER TABLE city ADD stock_or INT NOT NULL');
        $this->addSql('ALTER TABLE city ADD bois INT NOT NULL');
        $this->addSql('ALTER TABLE city ADD pierre INT NOT NULL');
    }
}
