<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260827151119 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE city (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(80) NOT NULL, difficulte INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE family (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(60) NOT NULL, renommee INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE game_save (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, mode VARCHAR(255) NOT NULL, mission INT DEFAULT NULL, cycle INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_opened_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, joueur_id INT NOT NULL, famille_id INT NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BE7356F2A9E2D76C ON game_save (joueur_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BE7356F297A77B84 ON game_save (famille_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BE7356F2A73F0036 ON game_save (ville_id)');
        $this->addSql('ALTER TABLE game_save ADD CONSTRAINT FK_BE7356F2A9E2D76C FOREIGN KEY (joueur_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_save ADD CONSTRAINT FK_BE7356F297A77B84 FOREIGN KEY (famille_id) REFERENCES family (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE game_save ADD CONSTRAINT FK_BE7356F2A73F0036 FOREIGN KEY (ville_id) REFERENCES city (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE game_save DROP CONSTRAINT FK_BE7356F2A9E2D76C');
        $this->addSql('ALTER TABLE game_save DROP CONSTRAINT FK_BE7356F297A77B84');
        $this->addSql('ALTER TABLE game_save DROP CONSTRAINT FK_BE7356F2A73F0036');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE family');
        $this->addSql('DROP TABLE game_save');
    }
}
