<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260827201255 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE expedition (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(255) NOT NULL, duree_en_cycles INT NOT NULL, avancement_en_dixiemes INT NOT NULL, ville_id INT NOT NULL, destination_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_692907EA73F0036 ON expedition (ville_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EXPEDITION_PAR_ZONE ON expedition (destination_id)');
        $this->addSql('ALTER TABLE expedition ADD CONSTRAINT FK_692907EA73F0036 FOREIGN KEY (ville_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE expedition ADD CONSTRAINT FK_692907E816C6140 FOREIGN KEY (destination_id) REFERENCES zone (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE expedition DROP CONSTRAINT FK_692907EA73F0036');
        $this->addSql('ALTER TABLE expedition DROP CONSTRAINT FK_692907E816C6140');
        $this->addSql('DROP TABLE expedition');
    }
}
