<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Les dossiers d'enquête, et les cases déjà fouillées (lot 7.3).
 *
 * Rien à reprendre : les parties existantes n'ont ouvert aucun dossier, et
 * aucune de leurs cases n'a été fouillée — c'est exactement leur état.
 */
final class Version20260831101721 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Enquêtes : dossiers, indices versés, cases fouillées';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE dossier_denquete (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, enquete VARCHAR(40) NOT NULL, statut VARCHAR(20) NOT NULL, indices JSON NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_52772708A73F0036 ON dossier_denquete (ville_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_DOSSIER_PAR_VILLE ON dossier_denquete (ville_id, enquete)');
        $this->addSql('ALTER TABLE dossier_denquete ADD CONSTRAINT FK_52772708A73F0036 FOREIGN KEY (ville_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE zone ADD indice_recueilli BOOLEAN NOT NULL DEFAULT false');
        $this->addSql('ALTER TABLE zone ALTER indice_recueilli DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE dossier_denquete DROP CONSTRAINT FK_52772708A73F0036');
        $this->addSql('DROP TABLE dossier_denquete');
        $this->addSql('ALTER TABLE zone DROP indice_recueilli');
    }
}
