<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260830114725 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE route_commerciale (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, partenaire VARCHAR(40) NOT NULL, route VARCHAR(255) NOT NULL, quinzaines_avant_ouverture INT NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E0A2A757A73F0036 ON route_commerciale (ville_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ROUTE_PAR_VILLE ON route_commerciale (ville_id, partenaire)');
        $this->addSql('ALTER TABLE route_commerciale ADD CONSTRAINT FK_E0A2A757A73F0036 FOREIGN KEY (ville_id) REFERENCES city (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE route_commerciale DROP CONSTRAINT FK_E0A2A757A73F0036');
        $this->addSql('DROP TABLE route_commerciale');
    }
}
