<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260828191846 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE employee (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, competence INT NOT NULL, salaire INT NOT NULL, anciennete_probable INT NOT NULL, traits JSON NOT NULL, specialite VARCHAR(255) DEFAULT NULL, actifs_amenes INT NOT NULL, inactifs_amenes INT NOT NULL, prend_poste_au_cycle INT NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5D9F75A1A73F0036 ON employee (ville_id)');
        $this->addSql('CREATE TABLE job_offer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, candidatures JSON NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_288A3A4EA73F0036 ON job_offer (ville_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_OFFRE_PAR_BATIMENT ON job_offer (ville_id, type)');
        $this->addSql('ALTER TABLE employee ADD CONSTRAINT FK_5D9F75A1A73F0036 FOREIGN KEY (ville_id) REFERENCES city (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE job_offer ADD CONSTRAINT FK_288A3A4EA73F0036 FOREIGN KEY (ville_id) REFERENCES city (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE employee DROP CONSTRAINT FK_5D9F75A1A73F0036');
        $this->addSql('ALTER TABLE job_offer DROP CONSTRAINT FK_288A3A4EA73F0036');
        $this->addSql('DROP TABLE employee');
        $this->addSql('DROP TABLE job_offer');
    }
}
