<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * La ville héberge des maisonnées (lot 4.1).
 *
 * La population cesse d'être une formule dérivée du Quartier d'habitation pour
 * devenir un effectif réel : la somme des personnes des foyers installés.
 */
final class Version20260828141216 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajoute la table foyer et installe une famille fondatrice dans chaque ville existante.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE foyer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, adultes INT NOT NULL, ages_des_enfants JSON NOT NULL, ville_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4EB44E88A73F0036 ON foyer (ville_id)');
        $this->addSql('ALTER TABLE foyer ADD CONSTRAINT FK_4EB44E88A73F0036 FOREIGN KEY (ville_id) REFERENCES city (id) NOT DEFERRABLE');

        // Une ville sans foyer n'aurait aucun habitant : elle ne mangerait
        // rien, ne fournirait aucun bras, et son compteur de population
        // afficherait zéro. Les parties déjà en cours reçoivent donc leur
        // famille fondatrice.
        //
        // Deux adultes sans enfant, et non un foyer tiré au sort : une
        // migration doit produire le même résultat à chaque exécution, et on
        // n'invente pas rétroactivement des enfants à une famille déjà
        // installée. C'est aussi la composition la plus frugale, celle qui
        // risque le moins de mettre en famine une partie en cours.
        $this->addSql("INSERT INTO foyer (ville_id, adultes, ages_des_enfants) SELECT id, 2, '[]' FROM city");
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE foyer DROP CONSTRAINT FK_4EB44E88A73F0036');
        $this->addSql('DROP TABLE foyer');
    }
}
